<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <!-- do 'dotnet test -p:NativeAotTestMode=true' from the commandline to run the tests in native aot black-box testing mode -->
    <!-- or change 'true' to '' below to make your ide test runner do aot black-box testing -->
    <ItemGroup Condition="'$(NativeAotTestMode)' == 'true'">
        <RuntimeHostConfigurationOption Include="NativeAotTestMode" Value="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints.Testing" Version="8.3.0-rc.1"/>
        <PackageReference Include="Shouldly" Version="4.3.0"/>
        <PackageReference Include="xunit.v3" Version="4.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Source\MyApp.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="Always"/>
    </ItemGroup>

</Project>